languageCode = "en-us"
title = "Dimension"
baseurl = "http://example.org/"
theme = "dimension"

[params]
  title = "Brodes"
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "Youtube"
  icon = "Youtube"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"
